services:

  # ==========================================================
  # FASTAPI BACKEND
  # ==========================================================

  api:

    build: .

    container_name: karachi-aqi-api

    ports:

      - "${API_PORT:-8000}:8000"

    env_file:

      - .env

    volumes:

      - ./feature_repo/feature_repo/data:/app/feature_repo/feature_repo/data

    restart: unless-stopped


  # ==========================================================
  # STREAMLIT FRONTEND
  # ==========================================================

  frontend:

    build: .

    container_name: karachi-aqi-frontend

    command: >

      streamlit run frontend/app.py
      --server.address 0.0.0.0
      --server.port 8501

    ports:

      - "8501:8501"

    environment:

      API_URL: http://api:8000

    depends_on:

      - api

    restart: unless-stopped


  # ==========================================================
  # FEATURE UPDATE SCHEDULER
  # ==========================================================

  scheduler:

    build: .

    container_name: karachi-aqi-scheduler

    command: python src/scheduler.py

    env_file:

      - .env

    volumes:

      - ./feature_repo/feature_repo/data:/app/feature_repo/feature_repo/data

    depends_on:

      - api

    restart: unless-stopped